#docker build -t amedice/elasticsearch .
#docker run -d -it -p 9200:9200 --name elasticsearch amedice/elasticsearch
#docker exec -it elasticsearch /bin/bash
#docker rm -f elasticsearch

FROM centos
MAINTAINER Alex S. Médice <alex.medice@gmail.com>

# Upgrading system
RUN yum -y upgrade

# Install tools
RUN yum -y install wget

# Install Java
RUN yum install -y java-1.8.0-openjdk

# Install Elasticsearch
RUN adduser elasticsearch
WORKDIR /home/elasticsearch
RUN wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.0.2.tar.gz
RUN sha1sum elasticsearch-5.0.2.tar.gz 
RUN tar -xzf elasticsearch-5.0.2.tar.gz
RUN mv /home/elasticsearch/elasticsearch-5.0.2/ /opt/elasticsearch-5.0.2

# Run
#RUN cd /opt/elasticsearch-5.0.2 && ./bin/elasticsearch