#docker build -t amedice/elasticsearch .
#docker run -d -it -p 9200:9200 --name elasticsearch amedice/elasticsearch
#docker exec -it elasticsearch /bin/bash
#docker rm -f elasticsearch

FROM centos
MAINTAINER Alex S. Médice <alex.medice@gmail.com>