#docker build --rm -t amedice/logstash .
#docker run -d --name logstash amedice/logstash
#docker exec -it logstash /bin/bash
#docker rm -f logstash

FROM logstash
MAINTAINER Alex S. Médice <alex.medice@gmail.com>

#RUN logstash-plugin install logstash-filter-de_dot
#COPY logstash.conf /some/config-dir/

#CMD ["-f", "/some/config-dir/logstash.conf"]